/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package br.com.dumba.labs;

public final class Manifest {
    public static final class permission {
        public static final String MAPS_RECEIVE="br.com.dumba.labs.permission.MAPS_RECEIVE";
    }
}
